baseURL = "https://hugotion.github.io/j5761h6pjcf18sgchfbn2zdf217hyvfc/"
defaultLanguage = "en"
title = "MDFriday"
description = "MDFriday homepage, showcase the product or service."
theme = "theme-long-teng"

[params]
    Author = 'sunwei'